name: Publish Package to npmjs
on:
  push:
    branches:
      - main
jobs:
  main:
    if: "contains(github.event.head_commit.message, 'publish:')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.TARTPLUS_NPM_PUBLISH_TOKEN }}
